### PR TITLE
Request

### PR DESCRIPTION
**Pull request by Dimytrio**
Added sign up, footer, and login pages.

### CODE REVIEW

**Review by HuckWoody — APPROVED** [review]
Looks good. Only note is it looks like you pushed to the main and are updating the dev from the main.

**Comment by Dimytrio** [comment]
Yes I thought we were going to add all the folders into main and dev, and go from there? That's why I sent a request to update dev from main

**Comment by Dimytrio** [comment]
> Looks good. Only note is it looks like you pushed to the main and are updating the dev from the main.

Yes I thought we were going to add all the folders into main and dev, and go from there? That's why I sent a request to update dev from main

**Comment by HuckWoody** [comment]
Okay, yeah sounds good!

**Pull request merged**
